### ISSUE TITLE
OSC app does not work after app update

### ISSUE THREAD

**Issue by opix11** [magdesign/PocketVJ-CP-exh#11]
i am having trouble getting OSC to work, i am only trying it to stop all and start dmx playback01 but i cant seem to get it too work. i have had it working before on the old osc app, but not with the new osc app. 

i have also tried reverting to an old osc file that i had working a while back and it still does not seem to work. 

wifi is on, and i have the correct command, but still no luck! 

thanks!

**Comment by magdesign** [comment]
Can you send osc with any other device than your Android app
(one of [those](https://github.com/magdesign/PocketVJ-CP-exh/blob/master/sync/osc_control.js) commands).

Do you have release notes of osc app the see what they changed... which app exactly?
maybe you need to disable a firewall or https setting?

**Comment by opix11** [comment]
I’ll try disabling them! I did try the other day I think but I had no luck, I’ll try again! 

And the osc app is just touch osc, they bought out a new one not too long ago! 

I also tried autostart with osc and still had no luck! 

Thanks! 

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
**Make sure you set the IP address and port right in your app!**
Make sure there is no firewall or Android/Apple security feature blocking OSC traffic.

I just tried our [touchOSC Preset](https://github.com/magdesign/PocketVJ-CP-exh/blob/master/sync/PocketVJ_OSC.touchosc) on the newest touchOSC version and everything works as expected. SO I need proper instructions on how to reproduce your issue.

please re-check:
you can access via webbrowser to the cp?
if yes, go to "DMX OSC MIDI" and click listen to "Start Listen to Port: 9876"

Send an osc command like: oscsend 192.168.2.100 9876 /startmaster
or whatever your ip is.

**Comment by magdesign** [comment]
![osc_sending](https://user-images.githubusercontent.com/5273166/128139760-bd3fe2e8-2f11-42a1-850e-5abdf311ed5f.png)

**Comment by opix11** [comment]
I’m just trying this now! The web browser works perfect, just not touch osc, I have my host set at 2.0.0.100 so maybe this is the problem? I’ll keep you posted 

Greg Jones. 
07884264516

**Comment by opix11** [comment]
I’m still trying different things and can’t get it too work which is strange!

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
Could you solve this?

**Comment by opix11** [comment]
Hi!

so it wasent working, but then after leaving it for a around  5 days,
turning it on, not changing any settings or any of the touch osc settings,
it did start working.
im confused how it happened but im going to reset the pocket vj once its
back of this job and try it again to see if i have the issue again or if
its fixed itself!

thankyou!
Greg jones

**Comment by opix11** [comment]
Hello! 

Hope you are well!

I’m having some issues with touch osc and my exhibition. 

Running the latest update, the dmx playback options do not loop, also, after I try and playback dmx playback after number 5 over touch osc it does not playback. 

Also, if I have the button set to momentary it keeps making the dmx jump, if I change it to toggle release it works perfectly- also momentary works on the old version of touch osc perfect. 

Hope your okay! Thank you!



Greg Jones. 
07884264516

**Comment by opix11** [comment]
Also- playback 5 only seems to playback a few seconds of the dmx 

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
How do you start dmx playback via osc (your exact command)?

Since there where no changes in the scripts since CP 4.0.7 I need more info to reproduce your trouble.

**Comment by opix11** [comment]
Hello!

So I’ve found the folder osc.control .js and wrote in dmx playback up too 22 and it works- only issue now is auto start osc isn’t working again- I can turn on osc through the terminal but it stops after around 5 minutes of playing dmx show- is there any ideas for this!?

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
Are you turning on OSC via terminal like this:` /var/www/sync/osc_start`

When clicking in CP Autostart `OSC/ArtNet/UDP` your osc listener is not working after a reboot?

I need exact info to help you fix your trouble and possible issues in the software.

BTW.
Should I update the `osc_control.js` script with more commands, if yes, what you need?

**Comment by opix11** [comment]
I am now! I wasent- but now when I do the /
> 
>  /var/www/sync/osc_start
> 
> 
> 
I get errors! 

When I click osc artnet auto start on the webpage my listener is not working! 

And it’s okay! I updated it just to have dmx playback and record commands up too 22 in it! 

Thanks :) 
Greg Jones. 
07884264516

**Comment by opix11** [comment]
Greg Jones. 
07884264516

**Comment by opix11** [comment]
So I have the dmx show starting over terminal also- but osc only stops all and doesn’t play the dmx shows- not sure why this is as if I type in to terminal the dmx playback command the same as what I have in touch osc it does start 

Greg Jones. 
07884264516

**Comment by opix11** [comment]
So I now have osc control, but only up to show 5! 

Greg Jones. 
07884264516

**Comment by opix11** [comment]
Okay- so, good news! 

I updated the control.js folder in home/pvj/osc and now I have control over all dmx playback. 

Osc is on start which is good, I’m not sure what got it working but I just kept punching that command you sent into terminal and eventually it started to come on! 

The only thing it says in terminal is it’s saying system too slow? 

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
If you updated with the Alternative Update method, you must click afterwards the `Update Everything` button since this fixes a lot of new things!

You can ignore the system is to slow message since it will work as expected (I tested this!)
What you can do under `System Settings` is to disable LIRC, Samba and Shell, this will free up some resources.

**Comment by opix11** [comment]
Hello! 

So only a quick one- the dmx shows after show 5 do not black out between changing shows, they overlap if you understand? 

Thanks 

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
I dont get what you mean...

**Comment by opix11** [comment]
So- for example- if I have dmx show playback on touch osc for show 1 - 10.

When I click between show 1-5 it stops the previous show and plays the next one. 

If I play show one, then hit show 7 without hitting stop all the. It does a weird glitch where it tries to playback both dmx shows 

Greg Jones. 
07884264516

**Comment by magdesign** [comment]
ok, can you try with newest version CP4.2.3
made some changes in the startshow 5-10 scripts.
