### ISSUE TITLE
Cp is not working 

### ISSUE THREAD

**Issue by balejandrovb** [magdesign/PocketVJ-CP-exh#2]
I just bought the pocketvj, but the cp is not working, I have updated by filezilla with the available version but it does not work, I need to start working as soon as possible, please help me

**Comment by magdesign** [comment]
Can you please describe in more detail what exactly is not working, 
your order number, your OS and browser version.

**Comment by balejandrovb** [comment]
My OS is Windows 10 64 bits , my browser version is Google Chrome  85.0.4183.102 (Build oficial) (64 bits), but I have already dealt with the mobile and have the same problem , 
none of the control panel icons work this is the only but important problem
![pocketvj](https://user-images.githubusercontent.com/70526221/93796406-6c931700-fc00-11ea-90f1-fbd10a0b7b39.jpg)

my Order number is 384 
![WhatsApp Image 2020-09-21 at 11 52 15 AM](https://user-images.githubusercontent.com/70526221/93796819-fa6f0200-fc00-11ea-95c1-28187de622df.jpeg)
 thanks

**Comment by magdesign** [comment]
Give me a moment, I found the problem.... will post here when the update is online....
I am very sorry for the trouble.
line 1675 in index.php contained a link to a online .js lib, but it should be:  <script src="../js/jquery-3.3.1.min.js" type="text/javascript"></script>

**Comment by balejandrovb** [comment]
thanks , im waiting the solution  :)

**Comment by magdesign** [comment]
Please download again the update and then 
update via filezilla, you need to upload only the index.php to the PocketVJ (to save some time).

**Comment by balejandrovb** [comment]
thanks , already is working,
Thanks for the attention

**Comment by magdesign** [comment]
Thank you for reporting!
