### ISSUE TITLE
Delay when starting a video file

### ISSUE THREAD

**Issue by ElSagnol** [magdesign/PocketVJ-CP-exh#5]
Hi! 
I'm trying for the first time the Exhibitions I get from you today.
OSC via Qlab is working super well, but there is about 4 sec latency when I send a osc trig.
Is it possible to reduce that time?
Thanks for your reply.

**Comment by magdesign** [comment]
The delay is caused by the stopall* script which is called before a video starts.
I could make you a few custom scripts which do not call this function, but then you must be sure that nothing else is running before you start a video!
How many custom videos do you like to trigger with OSC?

*stopall=> killing all running tasks to make sure there is no other video, mapper, audio etc. playing when you trigger something new

**Comment by ElSagnol** [comment]
I'm not sure for now, but I think 12 or 15 video on a pvj..

**Comment by magdesign** [comment]
Ok.
I just made an update to CP 3.1.5 please [download](https://pocketvj.com/downloads/PocketVJ-CP-exh.zip) and install it
(see [here](https://vimeo.com/467914288) or [here](https://vimeo.com/468128933) the 2nd one is the faster way).
Then you will have 5 new OSC commands to trigger videos with names from 01_ to 05_
This ones will not do any stopall command and also will not send a syncing timecode, they will loop forever until you send a stopall command.

the osc commands are:

/startlesser01
/startlesser02
/startlesser03
/startlesser04
/startlesser05

and keep in mind to send:
/stopall
to stop the tasks

please report back if it is faster and if it fits your needs or do you want them to play only once?
If you are happy I will write another 10 commands.

**Comment by ElSagnol** [comment]
Thanks for that, super..
For now It's doesn't work... I'll do again everything tomorrow to be sure... now I need to leave..
I'll report back asap but I can tell you I'll play only once each.

**Comment by magdesign** [comment]
ok. no worries, I should stop too :-)
I need to make a proper update video for the PVJ Exhibition.

**Comment by magdesign** [comment]
I made you an update tutorial.... 
https://vimeo.com/467914288
https://vimeo.com/468128933

**Comment by magdesign** [comment]
Updated to CP 3.1.6
Now you have 10 new commands to trigger a video on the fast way without checking if there is something running.
They only play once.

/starlesseronce01
/starlesseronce02
/starlesseronce03
/starlesseronce04
/starlesseronce05
/starlesseronce06
/starlesseronce07
/starlesseronce08
/starlesseronce09
/starlesseronce10

Hope this helps boosting the speed as you needed...

**Comment by ElSagnol** [comment]
Hi..
thanks for all that things

on x.5, /startlesser01 is working well, reduce to about 1 sec which is really better! can we reduce more do you think?

Updated on x.6 but no start at all with /starlesseronce01

although maybe you miss a "t" with the "/start..."

I'm looking where these sentence are implemented for now..

**Comment by ElSagnol** [comment]
I think I found why..in the picture... found in osc-control.js

I'm trying to test that now!

<img width="964" alt="Capture d’écran 2020-10-14 à 15 54 27" src="https://user-images.githubusercontent.com/72819502/95999025-c5d41c00-0e35-11eb-879c-9d59a23c4bd1.png">

**Comment by magdesign** [comment]
Thanks for the feedback.
Yes, there are some typos, was a bit too fast on the road this morning....

it should be: `exec("/var/www/startlesseronce01");`
and the command im osc then: `/startlesseronce01`

I fixed it and just uploading it to the server and to github.
if you want to edit the file by yourself or replace just the osc_control.js
its located in` /var/www/sync/osc_control.js` or make an alternative update as described in the video.

I think 1second is the fastest to go. But the theater in france is solving it like this:
starting the video, then sending the /pause command, when they want to trigger on time, just send /pause again.

**Comment by ElSagnol** [comment]
Super.

After a tiny modification, it's working now!

Rename each sync/starlesseronce## in sync/startlesseronce##
completed in each sync/startlesseronce## . a # was missing to evitate killing all tasks..

where can I upload to give you that?
thanks for everything

**Comment by magdesign** [comment]
omg :-)
great, thanks!
its a shame that I again made a typo....
via email would be amazing.

**Comment by ElSagnol** [comment]
done

**Comment by magdesign** [comment]
Thank you!!
