### ISSUE TITLE
 How can I increase the volume of the video in the mapping application

### ISSUE THREAD

**Issue by balejandrovb** [magdesign/PocketVJ-CP-exh#6]
hi , i have a problem , the all videos i put in the mapping app , the volume is very low 
i need to set the audio in the hdmi and not on jack 3.5 mm
Can u help me ?
I ve a Exhibition Pocket vj .

**Comment by magdesign** [comment]
is audio playing on hdmi or only on jack ?

for hdmi playback I think I must recompile the mapper, I'll check it.
for turning up volume i might find a solution soon...currently compiling, need a moment until its finished

**Comment by balejandrovb** [comment]
i only can  put the audio  on jack , but i want to put the audio on hdmi 
i have a demostration tomorrow 12 pm . X_X
thanks

**Comment by magdesign** [comment]
hdmi should be possible, but need to recompile mapperFBO... this takes a few hours

note for myself:
edit: `ofxPiMapper/src/Sources/VideoSource.cpp`

change:
```
bool VideoSource::enableAudio = true;
bool VideoSource::useHDMIForAudio = true;
```

and recompile

**Comment by magdesign** [comment]
are you familiar with the terminal, ssh and compiling ?

I am on it...

**Comment by magdesign** [comment]
I am sorry, its not that simple to bring the mapping audio to HDMI signal.
Currently only Jack is supported for mapping.

**Comment by magdesign** [comment]
Since this issue has another titel.
Setting volume to 100% can be done in system settings, try it here:

![volume](https://user-images.githubusercontent.com/5273166/96095000-50685a00-0ece-11eb-9d13-5ae674f431ca.png)

its for all sound, I think I need to change the name of the button...

**Comment by balejandrovb** [comment]
hi thanks for the info
but this button only works with the video player , but not on the mapper 
all the videos i put on the mapper sounds too low
Thank u

**Comment by magdesign** [comment]
I see, working on it...

- Was able to manage HDMI out (its only possible to use HDMI or Jack, not both)
- Was able to pump volume

Now come the implementation for an update

**Comment by magdesign** [comment]
Release update CP to version 3.1.7
*****************************************

After update, go to Display and click:
![mapper2](https://user-images.githubusercontent.com/5273166/96250881-d7d9ca00-0faf-11eb-92cf-752c2d7d784f.png)
reboot to get it initialised (it changes some settings to enable hdmi audio).



Then go to System Setting, there you will find Mapper and Mapper HDMI
![mapper](https://user-images.githubusercontent.com/5273166/96251148-55053f00-0fb0-11eb-857d-b9ad7713ee70.png)



Update to one of them, when clicking the knob, wait until you see text in the output window, then you know its updated.
Audio volume will now be 100%
Depending on which one you select, audio will be sent over HDMI.
