### ISSUE TITLE
Play/Pause text on screen

### ISSUE THREAD

**Issue by ElSagnol** [magdesign/PocketVJ-CP-exh#7]
Hi

When I hit Pause on the web interface, There is no text appear on screen (time and co).
When I trig with OSC /pause, there is text on the screen like this pic.
any idea? I don't want text on screen?

EDIT : 
It appear only when I trig OSC `/startlesseronce01` or `/startlesser01`

**Comment by ElSagnol** [comment]
`/startlesser01`

**Comment by magdesign** [comment]
Can you edit the script: startlesser01 (`/var/www/sync/startlesser01`)

and change from 

`/usr/bin/omxplayer --loop -o both /media/internal/video/01* > /dev/null 2>&1 & echo $! &`

to
`/usr/bin/omxplayer --loop --no-osd -o both /media/internal/video/01* > /dev/null 2>&1 & echo $! &`

the `--no-osd` flag  might be the solution.

if this works I will update all the scripts tomorrow.

BTW.
to edit scripts you could also access the terminal from PocketVJ's Control Panel, there is a button in the red system tab, called "Terminal" (access the heart). Then login with userdata from papercard, to edit the mentioned script, type:
`sudo nano /var/www/sync/startlesser01`
edit it, 
then hit `Ctrl+x` and `y `to save it.

**Comment by ElSagnol** [comment]
Perfect! Thanks a lot.

EDIT : here is the entire folder with all scripts modified : [https://www.dropbox.com/s/pbn4ccd8570v809/PocketVJ-CP-exh.zip?dl=0](url) (/startlesser## and /startlesseronce##

**Comment by magdesign** [comment]
Thanks!
I need to fix my dev pipeline, then I will push the whole thing to this github repo, which makes much more sense to collaborate...
